#!/usr/bin/env bash

# Function to parse command-line arguments
parse_arguments() {
  # Set default values for variables
  local video_file=""
  local chromecast_ip=""
  local display_help=false

  # Parse command-line arguments
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -f|--file)
        video_file="$2"
        shift 2
        ;;
      -c|--chromecast)
        chromecast_ip="$2"
        shift 2
        ;;
      -h|--help)
        # Display usage message
        display_help=true
        shift
        ;;
      *)
        # Unknown option
        shift
        ;;
    esac
  done

  # Set default values for variables if they are not set
  if [[ -z "$video_file" ]]; then
    video_file="output.mp4"
  fi
  if [[ -z "$chromecast_ip" ]]; then
    chromecast_ip="192.168.0.32"
  fi

  # Return variables
  echo "$video_file" "$chromecast_ip" "$display_help"
}

# Function to stream video to Chromecast
stream_to_chromecast() {
  local video_file=$1
  local chromecast_ip=$2

  vlc --verbose "$video_file" --sout "#chromecast" --sout-chromecast-ip="$chromecast_ip" --demux-filter=demux_chromecast --loop
}

# Function to confirm user input
confirm_input() {
  local video_file=$1
  local chromecast_ip=$2

  read -p "Stream $video_file to Chromecast at $chromecast_ip? [y/n] " confirm
  if [[ "$confirm" =~ ^[Yy]$ ]]; then
    # Stream video to Chromecast
    stream_to_chromecast "$video_file" "$chromecast_ip"
  else
    echo "Aborting."
  fi
}

# Main function
main() {
  # Parse command-line arguments
  local video_file chromecast_ip display_help
  read -r video_file chromecast_ip display_help <<< "$(parse_arguments "$@")"

  if [[ "$display_help" = true ]]; then
    # Display usage message
    echo "Usage: $0 [-f|--file video_file] [-c|--chromecast chromecast_ip]"
  else
    # Confirm user input
    confirm_input "$video_file" "$chromecast_ip"
  fi
}

# Call main function
main "$@"
